import { useEffect, useState } from 'react';
import MeetUpList from '../components/meetups/MeetupList';

const DUMMY_MEETUPS = [
  {
    id: 'm1',
    title: 'My First Meetup',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Frauenkirche_and_Neues_Rathaus_Munich_March_2013.JPG/1280px-Frauenkirche_and_Neues_Rathaus_Munich_March_2013.JPG',
    address: 'My First Meetup address',
    description: 'This is the first meetup description',
  },
  {
    id: 'm2',
    title: 'My Second Meetup',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Englischer_Garten_M%C3%BCnchen.jpg/1280px-Englischer_Garten_M%C3%BCnchen.jpg',
    address: 'My Second Meetup address',
    description: 'This is the second meetup description',
  },
];

const HomePage = () => {
  const [loadedMeetups, setLoadedMeetups] = useState([]);

  useEffect(() => {
    // Sending a make believe http request and fetching data here
    const returnedData = DUMMY_MEETUPS;

    setLoadedMeetups(returnedData);
  }, []);

  return <MeetUpList meetups={loadedMeetups} />;
};
// This update simulates fetching data from a backend
// Although at first glance, it appears to work in the same way, there is one key difference
// On the first render cycle, the 'loadedMeetups' state is an empty array
// Once that render has finished, 'useEffect()' is called, which then "fetches data from the backend", and sets that data to the 'loadedMeetups' state
// Although this happens almost instantly, the meetup items are missing in the html page that we fetch from the server
// The pre-rendered html page generated by Next.js does not wait for this data to be fetched
// It always takes the result of the first render cycle, and returns that as the pre-rendered HTML code
// (view the page source to take a look at this)
// This is bad, because this pre-rendered HTML is what is seen by search engine crawlers, so when done this way, all content fetched from the database will be ignored by search engines
// Hence, the search engine optimisation is dog-shit

export default HomePage;
